name = "maresafe-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "PAYMENT_SESSIONS"
id = "ad31e1f30c0d4de48b7db2c8ff5dbf0c"

[[kv_namespaces]]
binding = "BYPASS_CODES"
id = "8297312154374ee59c22171ce184fe55"

workers_dev  = true
preview_urls = false

[[d1_databases]]
binding       = "DB"
database_name = "maresafe-db"
database_id   = "2ec22b61-8912-4850-aed1-e89808ff839b"

[vars]
ALLOWED_ORIGIN = "*"
CARD_URL       = "https://www.maresafe.eu/"

# Secrets — set via `wrangler secret put`:
#   STRIPE_SECRET_KEY
#   BROWSERLESS_TOKEN
#   MASTER_CODE
#   RESEND_API_KEY
